language: php

notifications:
  email: false

php:
  - "7.2"

before_script:
  - composer install

script:
  - vendor/phpunit/phpunit/phpunit

after_script:
  - php vendor/bin/test-reporter --stdout > codeclimate.json
  - curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)'